"""empty message

Revision ID: 2ad2d2435c07
Revises: 5ee90498d8f9
Create Date: 2024-03-17 14:38:21.688024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ad2d2435c07'
down_revision = '5ee90498d8f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_place', sa.Column('duty_place_num', sa.Integer(), nullable=True))
    op.add_column('t_place', sa.Column('is_deleted', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_place', 'is_deleted')
    op.drop_column('t_place', 'duty_place_num')
    # ### end Alembic commands ###
