"""empty message

Revision ID: 5ee90498d8f9
Revises: ad8db0420630
Create Date: 2024-03-11 12:40:51.133304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ee90498d8f9'
down_revision = 'ad8db0420630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 't_sys_role', ['role_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_sys_role', type_='unique')
    # ### end Alembic commands ###
