"""empty message

Revision ID: ad8db0420630
Revises: f35f4efa0e64
Create Date: 2024-03-05 12:34:55.507091

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad8db0420630'
down_revision = 'f35f4efa0e64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_minority_family_holidays', 'comments',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_minority_family_holidays', 'comments',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(collation='utf8mb4_general_ci'),
               existing_nullable=True)
    # ### end Alembic commands ###
