"""empty message

Revision ID: e4a8a414e6f4
Revises: 3de5de20bdbc
Create Date: 2024-02-06 14:33:36.938003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4a8a414e6f4'
down_revision = '3de5de20bdbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_duty_plan', sa.Column('status', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_duty_plan', 'status')
    # ### end Alembic commands ###
