"""empty message

Revision ID: f35f4efa0e64
Revises: e4a8a414e6f4
Create Date: 2024-02-29 12:54:10.900055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f35f4efa0e64'
down_revision = 'e4a8a414e6f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_duty_plan', sa.Column('is_week', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_duty_plan', 'is_week')
    # ### end Alembic commands ###
